services:
    proxy:
        volumes:
            - ./nginx/nginx.host.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'

    frontend:
        environment:
            - NEXT_PUBLIC_SERVER_URL=http://csvbachkhoa.shop:80
