services:
    proxy:
        volumes:
            - ./nginx/nginx.host.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/live/csvbachkhoa.shop/fullchain.pem:/etc/nginx/ssl/fullchain.pem
            - /etc/letsencrypt/live/csvbachkhoa.shop/privkey.pem:/etc/nginx/ssl/privkey.pem
        ports:
            - '80:80'

    frontend:
        environment:
            - NEXT_PUBLIC_SERVER_URL=http://csvbachkhoa.shop:80
