services:
    proxy:
        build: ./nginx
        ports:
            - '3000:80'
            - '443:443'
        depends_on:
            - frontend
            - backend

    backend:
        build: ./server
        expose:
            - 8000
        environment:
            - HOST=0.0.0.0
            - PORT=8000
            - ENV=production
            - AVATAR_FOLDER_DIR=/app/avatars
        depends_on:
            - db

    frontend:
        build:
            context: ./client
        environment:
            - NEXT_PUBLIC_SERVER_URL=http://localhost:3000
        expose:
            - 3000
        depends_on:
            - backend
    db:
        image: mysql:9.0.1
        ports:
            - '8989:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
