name: Testing

on:
    push:
        branches:
            - main

jobs:
    test-backend:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.8

            - name: Install virtualenv
              run: |
                  python -m pip install --upgrade pip
                  pip install virtualenv

            - name: Set up virtualenv
              run: |
                  cd server
                  python -m venv venv

            - name: Setup env
              run: |
                  cd server
                  mv .env.example .env

            - name: Install dependencies
              run: |
                  cd server
                  venv/bin/python -m pip install --upgrade pip
                  venv/bin/python -m pip install -r requirements.txt

            - name: Run tests
              run: |
                  cd server
                  venv/bin/python -m pytest

    test-frontend:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: |
                  cd client
                  npm install

            - name: Run Lint
              run: |
                  cd client
                  npm run lint

            - name: Run tests
              run: |
                  cd client
                  npm run test

    e2e-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Run Project
              run: |
                  docker compose up -d

            - name: Run tests
              uses: cypress-io/github-action@v6
              with:
                  working-directory: client
