name: Testing

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.8

            - name: Install virtualenv
              run: |
                  python -m pip install --upgrade pip
                  pip install virtualenv

            - name: Set up virtualenv
              run: |
                  cd server
                  python -m venv venv

            - name: Install dependencies
              run: |
                  cd server
                  venv/bin/python -m pip install --upgrade pip
                  venv/bin/python -m pip install -r requirements.txt

            - name: Run tests
              run: |
                  cd server
                  venv/bin/python -m pytest
